export const ADMIN_NAV_LINKS = [
  { href: "/admin", label: "Übersicht" },
  { href: "/admin/startseite", label: "Startseite" },
  { href: "/admin/verein", label: "Verein" },
  { href: "/admin/projekte", label: "Projekte" },
  { href: "/admin/kennzahlen", label: "Kennzahlen" },
  { href: "/admin/neuigkeiten", label: "Neuigkeiten" },
  { href: "/admin/erfolge", label: "Erfolge" },
  { href: "/admin/bilder", label: "Bilder" },
  { href: "/admin/spenden", label: "Spenden" },
  { href: "/admin/kontakt", label: "Kontakt" },
  { href: "/admin/wildseek", label: "WILDSEEK-Meldungen" },
  { href: "/admin/weidezaun", label: "Weidezaun-Meldungen" },
  { href: "/admin/interessenten", label: "Interessenten" },
] as const;
